site_name: Clovers' Blog
site_url: https://clovers2333.github.io/Clovers-Blog/
site_description: test1
repo_url: https://github.com/Clovers2333/Clovers-Blog/
repo_name: Clovers2333/Clovers-Blog
edit_uri: tree/master/docs
copyright: Copyright &copy; Clovers

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  # custom_dir: overrides
  features: # 功能  
    # - announce.dismiss # 可以叉掉公告的功能
    # - content.action.edit # 编辑按钮，似乎没啥用
    # - content.action.view # 查看按钮，似乎没啥用
    # - content.code.annotate # 代码注释，具体不清楚
    - content.code.copy # 复制代码按钮
    # - content.code.select # 选择代码按钮
    # - content.tabs.link # 链接标签
    # - content.tooltips # 不太清楚呢这个
    # - header.autohide # 自动隐藏header
    # - navigation.expand # 默认展开导航栏
    - navigation.footer # 底部导航栏
    - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
    # - navigation.instant # 瞬间加载 最好注释掉，多语言切换这个会导致跳回首页
    # - navigation.instant.prefetch # 预加载
    # - navigation.instant.progress # 进度条
    # - navigation.path # 导航路径， 目前好像没啥用
    # - navigation.prune # 只构建可见的页面
    - navigation.sections # 导航栏的section
    - navigation.tabs # 顶级索引被作为tab
    - navigation.tabs.sticky # tab始终可见
    - navigation.top # 开启顶部导航栏
    - navigation.tracking # 导航栏跟踪
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    - search.suggest # 搜索建议
    - toc.follow # 目录跟踪-页面右侧的小目录
    # - toc.integrate # 目录跟踪集成到左侧大目录中
  palette:
    - media: "(prefers-color-scheme)" # 主题颜色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font: # 字体，大概率不需要换
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

plugins:
  - search
  # - glightbox:
  #     width: 80%
  # - git-revision-date-localized:
  #     type: datetime
  #     timezone: Asia/Shanghai
  #     locale: zh
  #     enable_creation_date: true
  #     exclude:
  #       - index.md
  # - statistics:
  #     page_check_metadata: comment

not_in_nav: todo.md

nav:
  - Welcome:
    - 首页: index.md
    - 友链: links.md
  - 计算机基础:
    - Introduction:
      - MIT Missing Semester: cs/basic/MIT-Missing-Semester.md
  #   - Python:
  #   - 前端三件套:
  #     - jaca script:
  #     - css:
  #     - html:
      # - 计算机系统:
  # - 信息安全:
  # - 经济学:
  # - 杂项: 
  - 生活:
    - 读书笔记:
      - 万历十五年: life/reading/wanli_15.md
    - 总结:
      - 23-24寒假总结: life/summary/23-24_winter_summary.md

