site_name: Clovers' Blog
site_url: https://clovers2333.github.io/Clovers-Blog/
site_description: test1
repo_url: https://github.com/Clovers2333/Clovers-Blog/
repo_name: Clovers2333/Clovers-Blog
edit_uri: tree/master/docs
copyright: Copyright &copy; 2024 Clovers

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  # custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)" # 主题颜色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font: # 字体，大概率不需要换
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

plugins:
  - search
  # - glightbox:
  #     width: 80%
  # - git-revision-date-localized:
  #     type: datetime
  #     timezone: Asia/Shanghai
  #     locale: zh
  #     enable_creation_date: true
  #     exclude:
  #       - index.md
  # - statistics:
  #     page_check_metadata: comment

not_in_nav: todo.md

nav:
  - Welcome:
    - 首页: index.md
    - 友链: links.md
  - Computer Science:
    - Introduction:
      - MIT Missing Semester: cs/basic/MIT-Missing-Semester.md
      - Git Cheatsheet: cs/basic/git_cheatsheet.md
      - 程序设计与算法基础: cs/basic/fpa.md
    - Basic Languages:
      - Python:
        - CS61A: cs/languages/python/cs61a.md
        - cheatsheet: cs/languages/python/cheatsheet.md
  #   - 前端三件套:
  #     - jaca script:
  #     - css:
  #     - html:
    - Data Structure:
      - 数据结构基础: cs/ds/fds.md
      - 高级数据结构与算法分析:
        - Index: cs/ds/ads/index.md
        - 数据结构全家桶: cs/ds/ads/ds.md
        - 回溯: cs/ds/ads/back.md
        - 分治: cs/ds/ads/divide.md
        - 贪心和动态规划: cs/ds/ads/greedy_DP.md
        - NP 问题: cs/ds/ads/NP.md
        - 近似算法: cs/ds/ads/Appr.md
        - 局部搜索: cs/ds/ads/LocalSearch.md
        - 随机化: cs/ds/ads/rand.md
        - 并行计算: cs/ds/ads/parallel.md
        - 外部排序: cs/ds/ads/external.md
    - AI:
      - 人工智能引论:
        - Index: cs/ai/intro/index.md
        - 逻辑与推理: cs/ai/intro/logic.md
        - 搜索与求解: cs/ai/intro/search.md
        - 机器学习——监督学习: cs/ai/intro/ml_s.md
        - 机器学习——无监督学习: cs/ai/intro/ml_uns.md
        - 深度学习: cs/ai/intro/dl.md
        - 强化学习: cs/ai/intro/rl.md
        - 人工智能博弈: cs/ai/intro/game.md
    - System:
      - Languages:
        - CS61C: cs/system/languages/cs61c.md
        - Verilog Cheatsheet: cs/system/languages/v_cheatsheet.md
      - Operating System:
        - Index: cs/system/os/index.md
        - Introduction: cs/system/os/Intro.md
        - Structure: cs/system/os/Structure.md
        - Process: cs/system/os/Process.md
        - Scheduling: cs/system/os/Scheduling.md
        - Thread: cs/system/os/Thread.md
        - Synchronization: cs/system/os/Synchronization.md
      - Books:
        - CSAPP:
          - Index: cs/system/books/csapp/index.md
          - Labs: cs/system/books/csapp/labs.md
          - Bits, Bytes and Integer: cs/system/books/csapp/Lec2-3.md
          - Floating Points: cs/system/books/csapp/Lec4.md
          - Machine-Level Programming: cs/system/books/csapp/Lec5-9.md
          - Optimizing: cs/system/books/csapp/Lec10.md
          - Processor Structure: cs/system/books/csapp/Lec11-13.md
        - 数字逻辑与计算机组成: cs/books/system/dlco.md
        - Digital Design and Computer Architecture: cs/books/system/ddca.md
  # - 信息安全:
  - Economy & Finance:
    - 微观经济学: finance/micro.md
    - 公司金融:
      - Index: finance/corporate/index.md
      - 财务报表及模型: finance/corporate/intro.md
      - 现值计算及投资决策: finance/corporate/investment.md
      - 融资决策和资产定价: finance/corporate/financing.md
      - 股利政策: finance/corporate/dividend.md
  # - 杂项: 
  - Life:
    # - 读书笔记:
    #   - 万历十五年: life/reading/wanli_15.md
    - 总结:
      - 23-24寒假总结: life/summary/23-24_winter_summary.md

